resolver: lts-18.28
allow-newer: true

extra-deps:
- http2-2.0.6
- warp-3.3.14
- http2-client-0.10.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- warp-grpc-0.4.0.1
- stm-hamt-1.2.0.7
- stm-containers-1.2
- tracing-0.0.7.2
- tracing-control-0.0.7.3
- mu-schema-0.3.1.2
- mu-protobuf-0.4.2.0
- mu-rpc-0.5.0.2
- mu-lens-0.3.0.0
- mu-grpc-client-0.4.0.2
- mu-optics-0.3.0.1
- mu-grpc-server-0.5.0.0
- compendium-client-0.2.1.1
- mu-grpc-common-0.4.0.0
- mu-avro-0.4.0.4

